### ISSUE TITLE
Contig names can cause error

### ISSUE THREAD

**Issue by dturaev** [BinPro/CONCOCT#129]
Hi, I applied concoct as described in the documentation and ran into the error below. It seems to be related to the naming of contig identifiers: If they are called "contig-1", "contig-2" etc., it works; if they have numerical identifiers ("1", "2", ...), the error comes up.

The command was: `concoct -c 40 --coverage_file coverage.txt --composition_file contigs.fa -b concoct-results`

The file "coverage.txt" had this format:
contig_id   sample_1    sample_2
1   266.92  115.534
2   1248.293    1696.679

The error was:

```
/usr/lib64/python2.7/site-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
Traceback (most recent call last):
  File "/home/apps/python/bin/concoct", line 4, in <module>
    __import__('pkg_resources').run_script('concoct==0.4.0', 'concoct')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 517, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1436, in run_script
    exec(code, namespace, namespace)
  File "/home/apps/python/lib64/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 76, in <module>
    results = main(args)
  File "/home/apps/python/lib64/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 39, in main
    args.pca_components
  File "/home/apps/python/lib64/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/transform.py", line 5, in perform_pca
    pca_object = PCA(n_components=nc).fit(d)
  File "/home/apps/python/lib64/python2.7/site-packages/scikit_learn-0.15.2-py2.7-linux-x86_64.egg/sklearn/decomposition/pca.py", line 225, in fit
    self._fit(X)
  File "/home/apps/python/lib64/python2.7/site-packages/scikit_learn-0.15.2-py2.7-linux-x86_64.egg/sklearn/decomposition/pca.py", line 275, in _fit
    U, S, V = linalg.svd(X, full_matrices=False)
  File "/home/apps/python/lib/python2.7/site-packages/scipy-0.14.0-py2.7-linux-x86_64.egg/scipy/linalg/decomp_svd.py", line 100, in svd
    full_matrices=full_matrices, overwrite_a=overwrite_a)
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)
```

**Comment by alneberg** [comment]
Hi @dturaev,

sorry for not answering earlier, this must have slipped my attention somehow. In order to investigate your problem further, I would like to know the contents of your contigs.fa file. My first hypotheses are that this problem could either be caused by having to few contigs (I'm not sure if I've ever tried clustering only 2 contigs with concoct), or if the ids in the fasta file does not correspond to the ids in the coverage.txt file. If you can give me some further information, I'm happy to investigate further what the problem could be.

Cheers,
Johannes

**Comment by dturaev** [comment]
Hi Johannes,

the very same command worked if the contig identifiers were not numeric (>1, >2 etc.) but e.g. >contig-1, >contig-2 etc. So I don't think it depends on the content of the contigs.fa file. Also, the identifiers in the fasta file and in the coverage file do match.
My contigs.fa file has several thousands sequences, and it worked nicely after I changed the contig identifiers both in the fasta and in the coverage file.

Best,
Dmitrij

**Comment by jvollme** [comment]
#150

**Comment by alneberg** [comment]
Same as #150
