### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by etheleon** [BinPro/CONCOCT#136]
Hi, 
tried installing concoct both from pip and from git source. 

When i call concoct, it throws up the following errors

```
$ concoct
Traceback (most recent call last):
  File "/export2/home/uesu2/.pyenv/versions/2.7.8/bin/concoct", line 6, in <module>
    import vbgmm
ImportError: /export2/home/uesu2/.pyenv/versions/2.7.8/lib/python2.7/site-packages/vbgmm.so: undefined symbol: gsl_linalg_cholesky_invert
```

* my gcc was built in the local dir. 
* and i'm using anacoda (installed without error)
* my gsl is v1.9 (checked with gsl-config --version)
   however cpp programs which require the gsl headers will only compile if i ran it as such:
`gcc test.cpp -o main -lgsl -lgslcblas `

it'll only compile if i gave it the following command 

installation output

```
$ pip install concoct
Collecting concoct
  Using cached concoct-0.4.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): cython>=0.19.1 in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from concoct)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from concoct)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.12.0 in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from concoct)
Requirement already satisfied (use --upgrade to upgrade): pandas>=0.11.0 in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from concoct)
Requirement already satisfied (use --upgrade to upgrade): biopython>=1.62b in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from concoct)
Requirement already satisfied (use --upgrade to upgrade): scikit-learn>=0.13.1 in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from concoct)
Requirement already satisfied (use --upgrade to upgrade): nose==1.3.0 in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from concoct)
Requirement already satisfied (use --upgrade to upgrade): sphinx-rtd-theme>=0.1.6 in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from concoct)
Requirement already satisfied (use --upgrade to upgrade): Sphinx>=1.2.2 in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from concoct)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from pandas>=0.11.0->concoct)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from pandas>=0.11.0->concoct)
Requirement already satisfied (use --upgrade to upgrade): Pygments>=1.2 in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from Sphinx>=1.2.2->concoct)
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.7 in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from Sphinx>=1.2.2->concoct)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.3 in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from Sphinx>=1.2.2->concoct)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from python-dateutil->pandas>=0.11.0->concoct)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in ./.pyenv/versions/2.7.8/lib/python2.7/site-packages (from Jinja2>=2.3->Sphinx>=1.2.2->concoct)
Installing collected packages: concoct
  Running setup.py install for concoct
    building 'vbgmm' extension
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ic-concoct -I/export2/home/uesu2/.pyenv/versions/2.7.8/include/python2.7 -c c-concoct/vbgmmmodule.c -o build/temp.linux-x86_64-2.7/c-concoct/vbgmmmodule.o
    c-concoct/vbgmmmodule.c: In function 'driver':
    c-concoct/vbgmmmodule.c:121:28: warning: assignment discards 'const' qualifier from pointer target type
      ptBestCluster->szCOutFile = szFileStub;
                                ^
    c-concoct/vbgmmmodule.c:147:5: warning: implicit declaration of function 'gsl_blas_dgemm' [-Wimplicit-function-declaration]
         gsl_blas_dgemm (CblasNoTrans,CblasNoTrans,1.0,tData.ptTMatrix,ptBestCluster->aptSigma[k],0.0,ptTemp);
         ^
    c-concoct/vbgmmmodule.c: In function 'decomposeMatrix':
    c-concoct/vbgmmmodule.c:648:5: warning: implicit declaration of function 'gsl_linalg_cholesky_invert' [-Wimplicit-function-declaration]
         gsl_linalg_cholesky_invert(ptSigmaMatrix);
         ^
    c-concoct/vbgmmmodule.c: In function 'performMStep':
    c-concoct/vbgmmmodule.c:661:17: warning: unused variable 'ptSigmaMatrix' [-Wunused-variable]
         gsl_matrix* ptSigmaMatrix = gsl_matrix_alloc(nD,nD);
                     ^
    c-concoct/vbgmmmodule.c: In function 'calcVBL':
    c-concoct/vbgmmmodule.c:1393:7: warning: implicit declaration of function 'gsl_blas_dsymv' [-Wimplicit-function-declaration]
           gsl_blas_dsymv (CblasLower, 1.0, ptCluster->aptSigma[k], ptDiff, 0.0, ptR);
           ^
    c-concoct/vbgmmmodule.c:1395:7: warning: implicit declaration of function 'gsl_blas_ddot' [-Wimplicit-function-declaration]
           gsl_blas_ddot (ptDiff, ptR, &dT2);
           ^
    c-concoct/vbgmmmodule.c: In function 'writeTMeans':
    c-concoct/vbgmmmodule.c:1636:7: warning: implicit declaration of function 'gsl_blas_dgemv' [-Wimplicit-function-declaration]
           gsl_blas_dgemv (CblasNoTrans, 1.0,ptData->ptTMatrix,ptVector,0.0, ptTVector);
           ^
    c-concoct/vbgmmmodule.c: In function 'runRThreads':
    c-concoct/vbgmmmodule.c:1683:15: warning: variable 'iret' set but not used [-Wunused-but-set-variable]
       int         iret[N_RTHREADS];
                   ^
    gcc -pthread -shared -L/export2/home/uesu2/.pyenv/versions/2.7.8/lib -L/export2/home/uesu2/local/lib build/temp.linux-x86_64-2.7/c-concoct/vbgmmmodule.o -lgsl -lgslcblas -o build/lib.linux-x86_64-2.7/vbgmm.so
    changing mode of build/scripts-2.7/concoct from 644 to 755
    changing mode of /export2/home/uesu2/.pyenv/versions/2.7.8/bin/concoct to 755
Successfully installed concoct-0.4.0
```

**Comment by binnisb** [comment]
I guess you don't have the gsl installed?
gsl_linalg_cholesky_invert is at least a function from GSL and it seems
that it is not found.



Cheers,
Brynjar

**Comment by etheleon** [comment]
Hi I've installed gsl from source, 

simple cpp compiled successfully
```cpp
#include <gsl/gsl_alglin.h>
#include <iostream>

int main()
{
  std::cout << "Hello World!";
}
```

**Comment by etheleon** [comment]
managed to get it installed using

`CFLAGS="-lgsl -lgslcblas" python setup.py install`

tried running but met the following error
```
$ ./bin/concoct 
Traceback (most recent call last):
  File "./bin/concoct", line 6, in <module>
    import vbgmm
ImportError: /export2/home/uesu2/local/anaconda/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/vbgmm.so: undefined symbol: gsl_linalg_cholesky_invert
```

**Comment by etheleon** [comment]
it ended up to be a problem with the version of gsl installed. upgraded to 1.16

**Comment by binnisb** [comment]
Thanks for the update, which version were you using before the upgrade?


Cheers,
Brynjar

**Comment by etheleon** [comment]
gsl 1.9
