### ISSUE TITLE
 'import vbgmm' then 'ImportError: dlopen : Symbol not found'

### ISSUE THREAD

**Issue by yoyohashao** [BinPro/CONCOCT#137]
Dear Admin, this is my first time to run CONCOCT but it gave me this messeage. Is there anything wrong with ANACONDA? Thanks

(concoct_env)SEBASTIANs-MacBook-Pro:CONCOCT-0.4.0 FLFLFLLF$ which concoct
//anaconda/envs/concoct_env/bin/concoct
(concoct_env)SEBASTIANs-MacBook-Pro:CONCOCT-0.4.0 FLFLFLLF$ concoct -h
Traceback (most recent call last):
  File "//anaconda/envs/concoct_env/bin/concoct", line 4, in <module>
    __import__('pkg_resources').run_script('concoct==0.4.0', 'concoct')
  File "//anaconda/envs/concoct_env/lib/python2.7/site-packages/setuptools-13.0.2-py2.7.egg/pkg_resources/__init__.py", line 698, in run_script
  File "//anaconda/envs/concoct_env/lib/python2.7/site-packages/setuptools-13.0.2-py2.7.egg/pkg_resources/__init__.py", line 1616, in run_script
  File "/anaconda/envs/concoct_env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-macosx-10.5-x86_64.egg/EGG-INFO/scripts/concoct", line 6, in <module>
    import vbgmm
ImportError: dlopen(//anaconda/envs/concoct_env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-macosx-10.5-x86_64.egg/vbgmm.so, 2): Symbol not found: _gsl_linalg_cholesky_invert
  Referenced from: //anaconda/envs/concoct_env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-macosx-10.5-x86_64.egg/vbgmm.so
  Expected in: dynamic lookup

**Comment by alneberg** [comment]
Hi @yoyohashao,

yes this could be an Anaconda error. Did you previously use any other python virtual environment like virtualenv or virtualenv-burrito? These do not play well together with anaconda and you need to uninstall them before installing anaconda. Please let me know if this helps or if the issue seems to be something else.

**Comment by yoyohashao** [comment]
Hi Johannes,
Yesterday I updated my gsl packages from 1.9 to 1.16. Now I don’t have any problem. Thanks.

Fang Liu
PhD Candidate
Rm. 3-410 School of Life Sciences and Biotechnology
Shanghai Jiaotong University
Shanghai,China 200240
https://www.researchgate.net/profile/Fang_Liu37
