### ISSUE TITLE
cannot run dnadiff_dist_matrix.py

### ISSUE THREAD

**Issue by dong5600** [BinPro/CONCOCT#159]
Hello, I am trying to run dnadiff_dist_matrix.py to compare my bins. However, the program gave errors: 

2016-02-01 11:20:20,289:INFO:root:Checking dependencies
Traceback (most recent call last):
  File "/home/apps/CONCOCT/CONCOCT-0.4.1/scripts/dnadiff_dist_matrix.py", line 305, in <module>
    main(*parse_input())
  File "/home/apps/CONCOCT/CONCOCT-0.4.1/scripts/dnadiff_dist_matrix.py", line 268, in main
    verbose_check_dependencies(["dnadiff"])
  File "/home/apps/CONCOCT/CONCOCT-0.4.1/scripts/dnadiff_dist_matrix.py", line 254, in verbose_check_dependencies
    raise(Exception("{} not installed".format(p)))
Exception: dnadiff not installed

CONCOCT/0.4.1 was installed on a server cluster and I remotely used it using the script:
python <path for files> test_dnadiff_out inputpath/*.fasta

Can anyone help with this? Millions of thanks!

**Comment by alneberg** [comment]
Seems like you need to install mummer or make sure that the mummer command
dnadiff is available.

Hope this helps.

/ Johannes
Den 1 feb 2016 18:35 skrev "dong5600" <notifications@github.com>:

**Comment by dong5600** [comment]
Thanks a lot, Johannes. I loaded MUMmer, it seems working!

**Comment by dong5600** [comment]
Hello, I got some new error messages:
Traceback (most recent call last):
  File "/home/apps/CONCOCT/CONCOCT-0.4.1/scripts/dnadiff_dist_matrix.py", line 305, in <module>
    main(*parse_input())
  File "/home/apps/CONCOCT/CONCOCT-0.4.1/scripts/dnadiff_dist_matrix.py", line 294, in main
    "hclust_dendrogram.{}".format(plot_image_extension)))
  File "/home/apps/CONCOCT/CONCOCT-0.4.1/scripts/dnadiff_dist_matrix.py", line 183, in plot_dist_matrix
    dendrogram(link, labels=pdm.index, ax=ax)
TypeError: dendrogram() got an unexpected keyword argument 'ax'

I searched online and found that the python version might be the problem. The recommended version on CONCOCT webpage is 2.7.*, and I am using 2.7.3, which seems to be within the required versions. Is there any way I can fix it? Any suggestion is highly appreciated. Millions of thanks!

**Comment by alneberg** [comment]
Hi, I don't think your python version is a problem but you might wanna have
a look at your version of scipy. If you have the latest version we might
have to look into that closer.

Johannes
Den 1 feb 2016 19:17 skrev "dong5600" <notifications@github.com>:
