### ISSUE TITLE
how to install SpeedUp_MP branch?

### ISSUE THREAD

**Issue by kodragonP** [BinPro/CONCOCT#221]
Hi,
I want to install the SpeedUp_MP branch of concoct, I followed the workflow in https://stackoverflow.com/questions/53057000/how-to-change-git-checkout-to-original. No error was reported after the "setup.py install" step. However, when I tried to run concoct, I get the error as follow:
Traceback (most recent call last):
  File "/home/gene/wanglong/miniconda2/bin/concoct", line 4, in <module>
    __import__('pkg_resources').run_script('concoct==0.5.0', 'concoct')
  File "/home/gene/wanglong/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/gene/wanglong/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/home/gene/wanglong/miniconda2/lib/python2.7/site-packages/concoct-0.5.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 6, in <module>
    import vbgmm
ImportError: /home/gene/wanglong/miniconda2/lib/python2.7/site-packages/vbgmm.so: undefined symbol: omp_set_num_threads

Is this meant something else I should do to complete the installing?

**Comment by kodragonP** [comment]
Thank you for your reply! My system is CentOS 6.7, and OpenMP is OK (version201511).

**Comment by alneberg** [comment]
Hello @kodragonP, the speedup branch is now merged into master and can be installed by:

`conda install concoct`

This will only work on linux at the moment though.
