### ISSUE TITLE
running time

### ISSUE THREAD

**Issue by ucassee** [BinPro/CONCOCT#244]
Hi developer,
This is my first time to use concoct to extract bins from my metagenome.  It has been running for more than 24 hours and still doesn't finish. Meanwhile, I use matbet to process the same data. it finished in 2 hours.  I don't find  any argument about thread setting in concoct. So, I wonder whether there are some ways to speed up the progress or I mada some mistakes in the running process.
Hope to your reply!
Best regards

**Comment by alneberg** [comment]
Hello @ucassee!

It will most likely be the case that metabat finishes faster than concoct. However there is an argument `-t` which you have to use in order for it to run on more than 1 thread. The latest version of concoct (<1.0.0) allows for high level of parallelisation and should really be ran with as many threads you have.

**Comment by ucassee** [comment]
Hello @alneberg ！
Thanks for your reply! Maybe I need to upgrade my concoct which has no -t augments in it.

**Comment by ucassee** [comment]
Hello @alneberg , 
      I have trouble to run concoct now.  The ERROR is following. I don't know how to deal with it.
      Hope to your reply~
`/data2017/share/tools/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/Bio/Seq.py:345: BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring().
  BiopythonDeprecationWarning)

/data2017/share/tools/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/input.py:115: RuntimeWarning: divide by zero encountered in log
  cov.ix[:,cov_range[0]:cov_range[1]])
Traceback (most recent call last):
  File "/data2017/share/tools/miniconda3/envs/metawrap-env/bin/concoct", line 4, in <module>
    __import__('pkg_resources').run_script('concoct==0.4.0', 'concoct')
  File "/data2017/share/tools/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data2017/share/tools/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/data2017/share/tools/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 76, in <module>
    results = main(args)
  File "/data2017/share/tools/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 39, in main
    args.pca_components
  File "/data2017/share/tools/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/concoct-0.4.0-py2.7-linux-x86_64.egg/concoct/transform.py", line 5, in perform_pca
    pca_object = PCA(n_components=nc).fit(d)
  File "/data2017/share/tools/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/sklearn/decomposition/pca.py", line 221, in fit
    self._fit(X)
  File "/data2017/share/tools/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/sklearn/decomposition/pca.py", line 265, in _fit
    X = check_array(X)
  File "/data2017/share/tools/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/sklearn/utils/validation.py", line 360, in check_array
    % (n_samples, shape_repr, ensure_min_samples))
ValueError: Found array with 0 sample(s) (shape=(0, 139)) while a minimum of 1 is required.
`

**Comment by alneberg** [comment]
This looks like it's some kind of problem with the input file. I can see that you've since tried to install the latest version of concoct. Would it be ok if I only attend the debugging of the latest version?

Thanks

**Comment by ucassee** [comment]
> This looks like it's some kind of problem with the input file.
YES， I can run concoct (0.4.0) with other data . But this data is also important for me and it can by analysis by metabat and maxbin. So, could you please give me some advice to check what's wrong with it with running concoct?
Thanks

**Comment by alneberg** [comment]
I believe this problem was solved in #245.
