### ISSUE TITLE
ImportError: cannot import name GMM

### ISSUE THREAD

**Issue by jolespin** [BinPro/CONCOCT#252]
Can you update the GMM to https://scikit-learn.org/stable/modules/generated/sklearn.mixture.GaussianMixture.html so we don't have to downgrade sklearn to 0.19? 
```bash

(metagenomics_env) -bash-4.1$ concoct --version
Traceback (most recent call last):
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/metagenomics_env/bin/concoct", line 10, in <module>
    from concoct.cluster import cluster
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/metagenomics_env/lib/python2.7/site-packages/concoct/cluster.py", line 4, in <module>
    from sklearn.mixture import GMM
ImportError: cannot import name GMM
```

**Comment by jolespin** [comment]
I just realized I'm using version 0.4.0
