### ISSUE TITLE
'DataFrame' object has no attribute 'ix'

### ISSUE THREAD

**Issue by Naima16** [BinPro/CONCOCT#289]
Hello

I am running concoct command:
concoct --composition_file contigs_10K.fa --coverage_file coverage_table.tsv -b concoct_output/**

which generate this error:

Up and running. Check /lustre03/project/6006375/naima17/oral_microbiome/binning_concoct/concoct_output/log.txt for progress
Traceback (most recent call last):
  File "/home/naima17/virtual_env/Concoct/bin/concoct", line 4, in <module>
    __import__('pkg_resources').run_script('concoct==1.0.0', 'concoct')
  File "/home/naima17/virtual_env/Concoct/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/naima17/virtual_env/Concoct/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/home/naima17/virtual_env/Concoct/lib/python3.7/site-packages/concoct-1.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 88, in <module>
    results = main(args)
  File "/home/naima17/virtual_env/Concoct/lib/python3.7/site-packages/concoct-1.0.0-py3.7-linux-x86_64.egg/EGG-INFO/scripts/concoct", line 20, in main
    composition, cov, cov_range = load_data(args)
  File "/home/naima17/virtual_env/Concoct/lib/python3.7/site-packages/concoct-1.0.0-py3.7-linux-x86_64.egg/concoct/input.py", line 25, in load_data
    read_length = args.read_length
  File "/home/naima17/virtual_env/Concoct/lib/python3.7/site-packages/concoct-1.0.0-py3.7-linux-x86_64.egg/concoct/input.py", line 90, in load_coverage
    cov.ix[:,cov_range[0]:cov_range[1]] = cov.ix[:,cov_range[0]:cov_range[1]].add(
  File "/home/naima17/virtual_env/Concoct/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'

May be it's a python version issue?
Thanks in advance
Naima

**Comment by Marlinski95** [comment]
Hi! I am having the same issue! Has there been a solution to this? It seems like it is index data frame issue in the pandas methods in the script based on my readings. However, I am not sure if that is something we as enduser can/should try to fix.
Could anybody assist with this? @alneberg?
Any help would be greatly appreciated!
