### ISSUE TITLE
concoct_refine error

### ISSUE THREAD

**Issue by tangminBio** [BinPro/CONCOCT#295]
Hello,
"concoct_refine clustering_gt1000_R.csv original_data_gt1000.csv clustering_gt1000_scg_sort.csv > concoct_ref.out
/home/tm/miniconda3/envs/concoct_env/bin/python: symbol lookup error: /home/tm/miniconda3/envs/concoct_env/lib/python3.8/site-packages/../../libmkl_intel_thread.so: undefined symbol: omp_get_num_procs"

I got this error report, but I have the libmkl_intel_thread.so in the directory, and i do not know how to fix the second error "omp_get_num_procs"

could you please help me? Thanks a lot

**Comment by tangminBio** [comment]
I added the libiomp5.so file and anther error came: /home/tm/miniconda3/envs/concoct_env/lib/python3.8/site-packages/sklearn/decomposition/_pca.py:461: RuntimeWarning: invalid value encountered in true_divide
  explained_variance_ = (S ** 2) / (n_samples - 1)
Traceback (most recent call last):
  File "/home/tm/miniconda3/envs/concoct_env/bin/concoct_refine", line 81, in <module>
    main(args)
  File "/home/tm/miniconda3/envs/concoct_env/bin/concoct_refine", line 48, in main
    assigns = vbgmm.fit(np.copy(transform_k,order='C'), int(NK), args.seed, args.threads)
  File "c-concoct/vbgmm.pyx", line 19, in vbgmm.fit
TypeError: fit() takes exactly 5 positional arguments (4 given)
