### ISSUE TITLE
pandas.errors.EmptyDataError: No columns to parse from file

### ISSUE THREAD

**Issue by madhubioinfo** [BinPro/CONCOCT#296]
It runs fine on different file but it produces error when I run for different file. any suggestions?

Traceback (most recent call last):
  File "/shared/programs/CONCOCT/scripts/concoct_coverage_table.py", line 91, in <module>
    generate_input_table(args.bedfile, args.bamfiles, samplenames=samplenames)
  File "/shared/programs/CONCOCT/scripts/concoct_coverage_table.py", line 61, in generate_input_table
    df = pd.read_csv(fh, header=None, sep='\t')
  File "/usr/local/lib/python3.4/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.4/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.4/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.4/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.4/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__

**Comment by alneberg** [comment]
A first guess is that one of the input files are malformed in some way. Double check that the bedfile for example is correct. Second guess is that the samtools command is not returning a tab-separated file. Have a look at https://github.com/BinPro/CONCOCT/blob/823dcd670bc42f6ea4622881c2484cda6c253a76/scripts/concoct_coverage_table.py#L37 where the command is specified and perhaps try to run it manually and inspect the results.

Hope this helps!
