### ISSUE TITLE
setup.py missing modules requirement

### ISSUE THREAD

**Issue by EricDeveaud** [BinPro/CONCOCT#298]
Hello 

I'm currfently installing CONCOCT-1.1.0 fro tagger tarball (https://github.com/BinPro/CONCOCT/archive/1.1.0.tar.gz)
`setupu.py`  lacks the following module used by `dnadiff_dist_matrix.py`

while testing it I have the following errors with 

```
[gensoft@4d0b24757bd2 test_data]$ dnadiff_dist_matrix.py . bins/sample*.fa
2021-03-15 14:07:40,302:INFO:root:Checking dependencies
2021-03-15 14:07:40,302:INFO:root:Using /opt/gensoft/exe/MUMmer/3.23/bin/dnadiff
2021-03-15 14:07:40,302:INFO:root:Running dnadiff pairwise (this could take a while)
2021-03-15 14:07:40,377:INFO:root:Writing distance matrix to ./dist_matrix.tsv
Traceback (most recent call last):
  File "/opt/gensoft/exe/CONCOCT/1.1.0/bin/dnadiff_dist_matrix.py", line 317, in <module>
    main(*parse_input())
  File "/opt/gensoft/exe/CONCOCT/1.1.0/bin/dnadiff_dist_matrix.py", line 299, in main
    plot_dist_matrix(matrix, fasta_names,
  File "/opt/gensoft/exe/CONCOCT/1.1.0/bin/dnadiff_dist_matrix.py", line 163, in plot_dist_matrix
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

and once matplotlib is installed
```
[gensoft@4d0b24757bd2 test_data]$ dnadiff_dist_matrix.py . bins/sample*.fa
2021-03-15 14:08:53,925:INFO:root:Checking dependencies
2021-03-15 14:08:53,926:INFO:root:Using /opt/gensoft/exe/MUMmer/3.23/bin/dnadiff
2021-03-15 14:08:53,926:INFO:root:Running dnadiff pairwise (this could take a while)
2021-03-15 14:08:54,003:INFO:root:Writing distance matrix to ./dist_matrix.tsv
2021-03-15 14:08:54,075:INFO:matplotlib.font_manager:Generating new fontManager, this may take some time...
Traceback (most recent call last):
  File "/opt/gensoft/exe/CONCOCT/1.1.0/bin/dnadiff_dist_matrix.py", line 317, in <module>
    main(*parse_input())
  File "/opt/gensoft/exe/CONCOCT/1.1.0/bin/dnadiff_dist_matrix.py", line 299, in main
    plot_dist_matrix(matrix, fasta_names,
  File "/opt/gensoft/exe/CONCOCT/1.1.0/bin/dnadiff_dist_matrix.py", line 166, in plot_dist_matrix
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
```

regards

Eric

**Comment by alneberg** [comment]
Yes you will have to install those manually, they are not strictly needed for the main functionality (the `dnadiff_dist_matrix.py` is a bit of an extra). To keep the dependency list to a minimum I choose to exclude them from the main installation files.
