### ISSUE TITLE
dnadiff_dist_matrix.py test :: failure

### ISSUE THREAD

**Issue by EricDeveaud** [BinPro/CONCOCT#299]
as stated in documentatio I ran `dnadiff_dist_matrix.py test_dnadiff_out tests/test_data/bins/sample*.fa` but it fails with the following error 

```
[gensoft@4d0b24757bd2 CONCOCT-1.1.0]$ mkdir test_dnadiff_out
[gensoft@4d0b24757bd2 CONCOCT-1.1.0]$ dnadiff_dist_matrix.py test_dnadiff_out tests/test_data/bins/sample*.fa
2021-03-15 14:17:06,588:INFO:root:Checking dependencies
2021-03-15 14:17:06,588:INFO:root:Using /opt/gensoft/exe/MUMmer/3.23/bin/dnadiff
2021-03-15 14:17:06,588:INFO:root:Running dnadiff pairwise (this could take a while)
2021-03-15 14:17:06,664:INFO:root:Writing distance matrix to test_dnadiff_out/dist_matrix.tsv
/opt/gensoft/exe/CONCOCT/1.1.0/bin/dnadiff_dist_matrix.py:174: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  link = linkage(pdm, metric='euclidean', method='average')
Traceback (most recent call last):
  File "/opt/gensoft/exe/CONCOCT/1.1.0/bin/dnadiff_dist_matrix.py", line 317, in <module>
    main(*parse_input())
  File "/opt/gensoft/exe/CONCOCT/1.1.0/bin/dnadiff_dist_matrix.py", line 299, in main
    plot_dist_matrix(matrix, fasta_names,
  File "/opt/gensoft/exe/CONCOCT/1.1.0/bin/dnadiff_dist_matrix.py", line 174, in plot_dist_matrix
    link = linkage(pdm, metric='euclidean', method='average')
  File "/opt/gensoft/exe/CONCOCT/1.1.0/venv/lib/python3.8/site-packages/scipy/cluster/hierarchy.py", line 1068, in linkage
    n = int(distance.num_obs_y(y))
  File "/opt/gensoft/exe/CONCOCT/1.1.0/venv/lib/python3.8/site-packages/scipy/spatial/distance.py", line 2425, in num_obs_y
    raise ValueError("The number of observations cannot be determined on "
ValueError: The number of observations cannot be determined on an empty distance matrix.
```

**Comment by EricDeveaud** [comment]
sorry ignore. 
problem is located between keyboard and seat  ;-(
