### ISSUE TITLE
Error during concoct_coverage_table.py: TypeError

### ISSUE THREAD

**Issue by aparada** [BinPro/CONCOCT#303]
Hello,
I am running into the following error when trying to get the coverage table.
I'm running concoct through conda. My read files have been sorted and indexed and all files are in the same directory.
Any thoughts on what may be going on and how to fix?
Thanks!
Alma
```

$ concoct_coverage_table.py contigs_10K.bed OC*sorted.bam > coverage_table.tsv
Traceback (most recent call last):
  File "/scratch/users/aparada/miniconda3/envs/concoct_env/bin/concoct_coverage_table.py", line 91, in <module>
    generate_input_table(args.bedfile, args.bamfiles, samplenames=samplenames)
  File "/scratch/users/aparada/miniconda3/envs/concoct_env/bin/concoct_coverage_table.py", line 41, in generate_input_table
    sys.stderr.write(out)
TypeError: write() argument must be str, not bytes
```

**Comment by michoug** [comment]
Hi, I ran it one sample at a time and it worked for me for some reasons

**Comment by arijitnus** [comment]
Hi @aparada @michoug 
I can run one sample at a time, but doesn't work for all files at a time. Is there a way to combine the results into one coverage table? Kindly guide, if you managed to run for all files or somehow combined results from all files.
