### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by arijitnus** [BinPro/CONCOCT#320]
Hi @alneberg and concoct community
I am facing the following error, when trying to run concoct with multiple files. Howevere, with a single file, it does not generate any error. Could you help or provide any guidance? 

Traceback (most recent call last):
  File "/home/svu/e0512807/miniconda3/envs/concoct_env/bin/concoct_coverage_table.py", line 91, in <module>
    generate_input_table(args.bedfile, args.bamfiles, samplenames=samplenames)
  File "/home/svu/e0512807/miniconda3/envs/concoct_env/bin/concoct_coverage_table.py", line 41, in generate_input_table
    sys.stderr.write(out)
TypeError: write() argument must be str, not bytes

**Comment by arijitnus** [comment]
Suddenly, reinstalling concoct in a new conda environment using Anaconda seemed to solve the problem.
