### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by ramnageena11** [BinPro/CONCOCT#334]
what are issues and how to resolve this?
Thaks
RNS

I have got this error msg:
concoct_coverage_table.py contigs_10k.bed /media/majorram/Analysis_Data/singhrn/meta_assembly/mapping/s*.sorted.bam > coverage_table.tsv
/home/majorram/anaconda3/envs/binning/bin/concoct_coverage_table.py:18: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
samtools: /home/majorram/anaconda3/envs/binning/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /home/majorram/anaconda3/envs/binning/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /home/majorram/anaconda3/envs/binning/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
[E::idx_find_and_load] Could not retrieve index file for '/media/majorram/Analysis_Data/singhrn/meta_assembly/mapping/s1.sorted.bam'
ERROR: fail to open index BAM file '/media/majorram/Analysis_Data/singhrn/meta_assembly/mapping/s1.sorted.bam'
Traceback (most recent call last):
  File "/home/majorram/anaconda3/envs/binning/bin/concoct_coverage_table.py", line 91, in <module>
    generate_input_table(args.bedfile, args.bamfiles, samplenames=samplenames)
  File "/home/majorram/anaconda3/envs/binning/bin/concoct_coverage_table.py", line 41, in generate_input_table
    sys.stderr.write(out)
TypeError: write() argument must be str, not bytes

**Comment by ramnageena11** [comment]
Hi,
Could you suggest the solution for the error. Pls.

Thanks
rgds
Ram

**Comment by leonmhartman** [comment]
> ERROR: fail to open index BAM file...

Perhaps try indexing the BAM file? Also, see issue #307
